Trying to removing as much casting as possible for TR mod
ManasMods/ManasCore pull request #13
Opened 2023-09-19 07:35 UTC by minheragon12345

# Description
Adding methods that helps Tensura Skills in TR

## List of changes

- added methods to Skill and SKillInstance: onToggleOn/Off, onTick, onActivation, onRelease, onScroll, onRightClickBlock, onDamageEntity, onTouchEntity, onTakenDamage, onDeath and onRespawn.
- changed HealSkill

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code Refactoring (non-breaking change which improved the Code Quality)
- [ ] Breaking Code Refactoring (breaking change which improved the Code Quality)
- [ ] Documentation update (JavaDoc or Markdown change)

2023-09-20 11:37 UTC, Charismara requested changes

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Equipped like armor?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Is there a Mana System in ManasCore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Should this be part of the Skill System?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
What are Skill Modes?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:37 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Triggered by mods using this lib, not the lib itself.
Why isn't it triggered by manascore?

2023-09-20 11:39 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Equiped in Slots, like some skills are only toggable, in the old mod, they're called Passive Skills.

2023-09-20 11:40 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
No, but it will be used alot for both Skill and Magic, which is extended from manaskill so I thought this will get rid of lots of casting

2023-09-20 11:40 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Yeh, mastery in skill can give boost in damage and unlock different modes of the skill/magic.

2023-09-20 11:41 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
One skill can have many modes, for example Black Flame can have Flame Breath in mode 1 and Fire Ball in mode 2.

2023-09-20 11:41 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
There is no Skill Slot System in ManasCore, right?

2023-09-20 11:59 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
So 2 Options:

1. Add a common mana system in manascore. (this would share mana between multiple mods, not only TR)
2. Remove Mana from the ManasCore Skill and use it only in TR

2023-09-20 11:59 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Yeh, no

2023-09-20 12:01 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Then the `100` shouldn't be an unchangeable value and it should be located in the instance class not the skill class

2023-09-20 12:02 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
That sounds like something that should be handled by TR and not ManasCore.

2023-09-20 12:14 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    }
Then this should be part of TR and not ManasCore

2023-09-21 16:39 UTC, Charismara requested changes
just another 75 small changes. lol

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/BarrierNegateDamageEvent.java
> +}
Combine the event classes since all 3 Events got the same fields.

Example:
```java
public class SkillDamageEvent extends Event {
    @Getter
    private final LivingHurtEvent event;
    @Getter
    private final LivingEntity entity;
    @Getter
    private final DamageSource source;
    @Getter
    @Setter
    private float amount;

    public class PreCalculation extends SkillDamageEvent {} 
    public class Calculation extends SkillDamageEvent {}
    public class PostCalculation extends SkillDamageEvent {}
}
```

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/SkillReleaseEvent.java
> + */
javadoc improvement:

```
/**
 * This Event is fired right before {@link ManasSkill#onRelease} is invoked.
 * Cancel this event to prevent the {@link ManasSkill#onRelease} invocation.
 */
```

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/SkillScrollEvent.java
> + */
improve javadoc. see my prev examples

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/SkillTickEvent.java
> + */
improve javadoc. see my prev examples

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/SkillToggleEvent.java
> + */
improve javadoc. see my prev examples

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributes.java
> +    public static final RegistryObject<Attribute> BARRIER = registry.register("barrier", () -> new RangedAttribute("manascore.attribute.barrier.name", 0.0, 0, 10_000_000_000_000.0).setSyncable(true))
the max value seems to be a bit too much

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/HealSkill.java
> +        return amount;
This makes no sense

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/ClientEventListenerHandler.java
> +    public static void clientMouseScrolled(InputEvent.MouseScrollingEvent event) {
the event param can be `final`

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/ServerEventListenerHandler.java
> +        }
No need to fire those events on client side

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/ServerEventListenerHandler.java
> +            skillStorage.syncChanges();
sync on the end of `onEntityHurt` instead of 3 times

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/ServerEventListenerHandler.java
> +            skillStorage.syncChanges();
sync on the end of `onEntityHurt` instead of 3 times

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/TickEventListenerHandler.java
> +        });
use non functional for loop. it's a bit faster.

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/TickEventListenerHandler.java
> +    }
don't sync changes in the for loop.

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/TickEventListenerHandler.java
> +            return;
use `break` to exit a loop

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/client/keybinding/KeybindingRegistry.java
> +            keybindings.add(new ManasKeybinding("manascore.keybinding.test", InputConstants.KEY_X,
don't add a default key to test keybindings

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/client/keybinding/KeybindingRegistry.java
> +            keybindings.add(new ManasKeybinding("manascore.keybinding.test_action_once", InputConstants.KEY_C,
don't add a default key to test keybindings

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/network/toserver/RequestSkillActivationPacket.java
> +                    if (MinecraftForge.EVENT_BUS.post(new SkillActivationEvent(skillInstance, player, this.keyNumber))) continue;
do all skills get activated when this packet get's handled?

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/network/toserver/RequestSkillReleasePacket.java
> +                for (ManasSkillInstance skillInstance : storage.getLearnedSkills()) {
do all skills get released when this packet gets handled?

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/network/toserver/RequestSkillScrollPacket.java
> +                    optional.get().onScroll(player, delta < 0 ? -1 : 1);
why don't u pass the delta into the callback?

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/network/toserver/RequestSkillTogglePacket.java
> +                for (ManasSkillInstance skillInstance : storage.getLearnedSkills()) {
do all skills get toggled?

2023-09-21 16:39 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/ManasCore.java
> +        forgeEventBus.addListener(TickEventListenerHandler::onTick);
work with the event annotations

2023-09-22 09:55 UTC, Charismara requested changes

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Returning false will stop {@link LivingEntity} from using any feature of the skill.
use `@return` to add return value docs

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Returning false if this skill is not toggleable.
use `@return` to add return value docs

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param player   Affected {@link Player}
is it the player owning this skill?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param player   Affected {@link Player}
is it the player owning this skill?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param player   Affected {@link Player}
is it the player owning this skill?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param player   Affected {@link Player}
is it the player owning this skill?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param player    Affected {@link Player}
is it the player owning this skill?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param player   Affected {@link Player}
is it the player owning this skill?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onScroll(ManasSkillInstance instance, Player player, int direction) {
you should use an enum for the direction if direction is just up and down and no delta. 

btw why no delta?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param player    Affected {@link Player}
is it the player owning this skill?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param attacker Affected {@link LivingEntity}
2 times the same entity?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param entity   Affected {@link LivingEntity}
2 times the same entity?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param entity   Affected {@link LivingEntity}
what entity?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param entity   Affected {@link LivingEntity} - Attacked Entity
2 times the same entity?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Called when the {@link LivingEntity} owning this Skill gets hurt (after effects like Barriers is consumed the damage amount)
don't reference to a skill that doesn't exist in this lib. reference the prev callback instead.

and provide the prev and next callbacks using `@see` on the end of the javadoc

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * Called when the {@link LivingEntity} owning this Skill gets damaged (after armor, potion effects, etc. is calculated)
don't reference to stuff that might not exist in this lib. reference the prev callback instead.

and provide the prev and next callbacks using @see on the end of the javadoc

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param living   Affected {@link LivingEntity}
do you even need the living param if people can get it themself using the event param?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * Set the tag of this instance.
what is it used for?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * @param attacker Affected {@link LivingEntity}
2 times the same entity?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * @param entity   Affected {@link LivingEntity}
do you even need the other param if people can get it themself using the event param?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * @param entity   Affected {@link LivingEntity}
do you even need the other param if people can get it themself using the event param?
2 times the same entity?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * @param living   Affected {@link LivingEntity}
do you even need the other param if people can get it themself using the event param?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * @param living   Affected {@link LivingEntity}
do you even need the other param if people can get it themself using the event param?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * Cancel the event when return true.
wrong javadoc

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * Cancel the death event when return true.
wrong javadoc

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * @param living   Affected {@link LivingEntity}
do you even need the other param if people can get it themself using the event param?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +     * {@link PlayerEvent.PlayerRespawnEvent} invoking this callback
missing `@param`

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/SkillAPI.java
> +    }
i smell crashed here.

mark this method as client only.
move the code body into an internal class that is not accessed by the server at all.

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/SkillAPI.java
> +    }
mark this method as client only.
move the code body into an internal class that is not accessed by the server at all.

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/SkillAPI.java
> +    }
mark this method as client only.
move the code body into an internal class that is not accessed by the server at all.

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/SkillDamageEvent.java
> +    }
Think about an alternative to `Barrier` since barrier is not in ManasCore

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/SkillToggleEvent.java
> + * Cancel this event to prevent the {@link ManasSkill#onToggleOn} and {@link ManasSkill#onToggleOff} invocation.
`{@link ManasSkill#onToggleOn} or {@link ManasSkill#onToggleOff}`

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/event/SkillToggleEvent.java
> +public class SkillToggleEvent extends SkillEvent {
maybe add a boolean field that shows weather this skill is going to be toggled on or off

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributeHandler.java
> +        //Barrier
wrong comment ??

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/TickEventListenerHandler.java
> +    public static void onTick(final TickEvent.LevelTickEvent event) {
couldn't `LivingTickEvent` be used instead?

2023-09-22 09:55 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/TickEventListenerHandler.java
> +    }
do those methods need to be public?

2023-09-22 21:27 UTC, Charismara requested changes

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void addMasteryPoint(ManasSkillInstance instance, Player player) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onToggleOn(ManasSkillInstance instance, Player player) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onToggleOff(ManasSkillInstance instance, Player player) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onTick(ManasSkillInstance instance, Player player) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onPressed(ManasSkillInstance instance, Player player) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public boolean onHeld(ManasSkillInstance instance, Player player, int heldTicks) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onRelease(ManasSkillInstance instance, Player player, int heldTicks) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onScroll(ManasSkillInstance instance, Player player, double delta) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onRightClickBlock(ManasSkillInstance instance, Player player, BlockHitResult hitResult) {
can a living entity be used here instead of a player?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +    public void onBeingTargeted(ManasSkillInstance instance, LivingEntity target, LivingEntity attacker, LivingChangeTargetEvent event) {
are all params needed?

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @param event    Triggered {@link LivingAttackEvent}
add callback order to the javadoc. what gets executed first, second, ...

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
>       * @param event    Triggered {@link LivingHurtEvent}
add callback order to the javadoc. what gets executed first, second, ...

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     * @see SkillDamageEvent.Barrier
add callback order to the javadoc. what gets executed first, second, ...

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkill.java
> +     */
add callback order to the javadoc. what gets executed first, second, ...

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/ManasSkillInstance.java
> +    }
In what order are those callbacks called?

add that info to the javadoc

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/InternalSkillPacketActions.java
> +        ManasCoreNetwork.INSTANCE.sendToServer(new RequestSkillActivationPacket(packetSkills, keyNumber));
do the whole stuff in a client sided dist executor

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/InternalSkillPacketActions.java
> +    public static void sendSkillActivationPacket(int keyNumber) {
Add a reference to this in the `SkillAPI` class with a note that this method in for client side use only.

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/InternalSkillPacketActions.java
> +        ManasCoreNetwork.INSTANCE.sendToServer(new RequestSkillReleasePacket(packetSkills, keyNumber, heldTicks));
do the whole stuff in a client sided dist executor

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/InternalSkillPacketActions.java
> +        ManasCoreNetwork.INSTANCE.sendToServer(new RequestSkillTogglePacket(packetSkills));
do the whole stuff in a client sided dist executor

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/InternalSkillPacketActions.java
> +    public static void sendSkillReleasePacket(int keyNumber, int heldTicks) {
Add a reference to this in the `SkillAPI` class with a note that this method in for client side use only.

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/InternalSkillPacketActions.java
> +    public static void sendSkillTogglePacket() {
Add a reference to this in the `SkillAPI` class with a note that this method in for client side use only.

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/TickEventListenerHandler.java
> +        });
only tick stuff for the current entity

2023-09-22 21:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/client/keybinding/KeybindingRegistry.java
> +            keybindings.add(new ManasKeybinding("manascore.keybinding.skill", InputConstants.KEY_X, category,
no default keys in temp keybindings

2023-09-25 17:08 UTC, Charismara requested changes

2023-09-25 17:08 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/ServerEventListenerHandler.java
> +        MinecraftForge.EVENT_BUS.post(new SkillDamageEvent.PostBarrier(e));
Barrier is still not a valid name for those events.

Think about something else for example: `Summarize, Calculate, PostCalculate` or `PreCalculation, Calculation, PostCalculation`

2023-09-25 17:08 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/capability/skill/event/TickEventListenerHandler.java
> +    public static Multimap<UUID, TickingSkill> tickingSkills = ArrayListMultimap.create();
do u clean up this map?

For example if a player got packet loss and the release packet doesn't reach the server?
Or the player leaves the Server?

2023-10-02 09:31 UTC, Charismara requested changes

2023-10-02 09:31 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/api/skills/TickingSkill.java
> +            TickEventListenerHandler.tickingSkills.get(entity.getUUID()).remove(this);
no need to remove this manually. just return false and the `TickEventListenerHandler` removes it for you

2023-10-09 11:28 UTC, Charismara approved these changes

2023-10-09 11:28 UTC, merged