Language update for attributes
ManasMods/ManasCore pull request #8
Opened 2023-02-04 10:02 UTC by minheragon12345

# Description
Changed some minor language issue for custom attributes

## List of changes
- Jump Power
- Critical Chance
- Critical Multiplier

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-02-04 10:06 UTC, Charismara requested changes

2023-02-04 10:06 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributes.java
> +    public static final RegistryObject<Attribute> CRIT_MULTIPLIER = registry.register("crit_multiplier", () -> new RangedAttribute("manascore.attribute.crit_multiplier.name", 1.5, -1.5, 420).setSynca
why would u change the min value to `-1.5`?

2023-02-04 10:37 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributes.java
> +    public static final RegistryObject<Attribute> CRIT_MULTIPLIER = registry.register("crit_multiplier", () -> new RangedAttribute("manascore.attribute.crit_multiplier.name", 1.5, -1.5, 420).setSynca
Isnt it `vanilla damage + (weapon damage * crit attribute)` ? it's `weapon damage * (1.5 + crit attribute)`
<img width="452" alt="image" src="https://user-images.githubusercontent.com/29400456/216762281-33c8e64e-711d-4e1b-9d5c-2ff33d43b6ef.png">
u said this and it does work like that ^

2023-02-04 10:39 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributes.java
> +    public static final RegistryObject<Attribute> CRIT_MULTIPLIER = registry.register("crit_multiplier", () -> new RangedAttribute("manascore.attribute.crit_multiplier.name", 1.5, -1.5, 420).setSynca
therefore if the crit attribute is -1.5
the final damage will be `weapon damage * (1.5 - 1.5) = 0`

2023-02-04 14:27 UTC, Charismara commented on src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributes.java
> +    public static final RegistryObject<Attribute> CRIT_MULTIPLIER = registry.register("crit_multiplier", () -> new RangedAttribute("manascore.attribute.crit_multiplier.name", 1.5, -1.5, 420).setSynca
it is `vanilla * attribute`. 
see here: https://github.com/ManasMods/ManasCore/blob/1.19.2/master/src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributeHandler.java#L59

But the default amount of the attribute is 1.5 so by default a crit is 50% stronger. See here: https://github.com/ManasMods/ManasCore/blob/1.19.2/master/src/main/java/com/github/manasmods/manascore/attribute/ManasCoreAttributes.java#L22

2023-02-05 13:07 UTC, Charismara approved these changes

2023-02-05 13:08 UTC, merged